name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev ]
    tags:
      - '*.*'
  #pull_request: ~
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  to_gitlab:
    runs-on: ubuntu-18.04
    steps:                                              # <-- must use actions/checkout@v1 before mirroring!
      # File: .github/workflows/mirror.yml
      - uses: net-engine/github-repository-sync-action@v1
        with:
          # The SSH private key for SSH connection to the target repository.
          # We strongly recommend saving this value as a GitHub Secret and using deploy
          # keys within the target repository
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
          # The SSH-based URL to the target repository
          target_repo_url: ssh://git@web.wyf.wiki:10022/lewei50/hello.git

  
